version: '3.7'

services:
  ftp:
    image: onjin/alpine-vsftpd
    environment:
      PASSWORD: files
    ports:
      - '2100:21'
    volumes:
      - ./ftp_data:/home/files
  s3:
    image: localstack/localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: sa-east-1
      DATA_DIR: /tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - ./s3_data:/tmp/localstack/data
      - ./aws_scripts:/docker-entrypoint-initaws.d
